language: node_js
node_js:
  - "10"

sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH

after_install:
  - npm install -g pm2

cache:
  yarn: true
  directories:
    - node_modules